# Generated by Django 3.2 on 2023-10-27 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20231027_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='x1',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='x2',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='y1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='y2',
        ),
    ]
