# Generated by Django 3.2 on 2023-10-27 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_satellite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Satellite',
            new_name='SatelliteModel',
        ),
    ]
