# Generated by Django 3.2 on 2023-10-28 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_order_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='photo',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.photo'),
        ),
    ]
