# Generated by Django 3.2 on 2023-10-28 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_order_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='photo',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
