# Generated by Django 3.2 on 2023-10-28 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20231028_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.order'),
        ),
    ]
