# Generated by Django 3.2 on 2023-10-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20231028_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='longitude',
        ),
        migrations.AddField(
            model_name='order',
            name='points',
            field=models.JSONField(default='none', verbose_name='Координаты'),
            preserve_default=False,
        ),
    ]
