# Generated by Django 3.2 on 2023-10-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20231028_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('radius', models.FloatField(verbose_name='Радиус')),
            ],
        ),
    ]
