# Generated by Django 3.2 on 2023-10-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_badzone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BadZone',
            new_name='BadZoneModel',
        ),
    ]
